DsAdminSite/Controllers/PlayerVersionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DsAdminSite.Controllers
{
    [Authorize]
    public class PlayerVersionController : Controller
    {
        // GET: PlayerVersion
        public ActionResult Index()
        {
            return View();
        }
    }
}

DsAdminSite/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                @Html.ActionLink("Ace System Management", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-main">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

            </div>
            <div class="navbar-collapse collapse" id="navbar-main">
                <ul class="nav navbar-nav">
                    <li><a href="@Url.Action("Index", "Home")" class="@(ViewContext.RouteData.Values["controller"].ToString() == "Home" ? "nav-active" : "")">Group</a></li>
                    <li><a href="@Url.Action("Index", "PlayerVersion")" class="@(ViewContext.RouteData.Values["controller"].ToString() == "PlayerVersion" ? "nav-active" : "")">PlayerVersion</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li><a style="cursor:pointer" data-toggle="modal" data-target="#logout-modal-id"><i class="fa fa-sign-out"></i>Logout</a></li>
                </ul>
            </div>                      

        </div>
    </nav>

    @*Modal*@
    <div id="logout-modal-id" class="modal fade" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myModal-label">Log out</h4>
                </div>
                <div class="modal-body">
                    <p>Would you like to log out?</p>
                </div>
                <div class="modal-footer">
                    @using (Html.BeginForm("LogOut", "Account", FormMethod.Post))
                    {
                        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                        <button type="submit" class="btn btn-primary">Log out</button>
                    }
                </div>
            </div>
        </div>
    </div>

    <div class="container">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - ECS Company ACE System</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/lodash")
    @RenderSection("scripts", required: false)

</body>
</html>