DsAdmin/Controllers/SmtpGlobalController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DsAdmin.Models;
using DsAdmin.Models.ViewModels;
using DsDbLib;
using DsDbLib.Models;
using System.Web.Helpers;
using System.Net.Mail;
using DsKit.Extensions;

namespace DsAdmin.Controllers
{
    [Authorize]
    public class SmtpGlobalController : Controller
    {
        private DsDb db = new DsDb();

        // GET: SmtpGlobalServiceViewModels
        public ActionResult Index()
        {
            var data = db.EmailService.Select(o => new SmtpGlobalServiceViewModel()
            {
                AllowAnonymous = o.AllowAnonymous,
                EnableSSL = o.EnableSSL,
                Id = o.Id,
                SenderAddress = o.SenderAddress,
                SenderName = o.SenderName,
                SmtpAccount = o.SmtpAccount,
                SmtpPassword = o.SmtpPassword,
                SmtpPort = o.SmtpPort,
                SmtpServerAddress = o.SmtpServerAddress
            });

            ViewBag.ServiceCount = db.EmailService.Count();

            return View(data);
        }

        // GET: SmtpGlobalServiceViewModels/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var emailService = db.EmailService.Find(id);

            var smtpGlobalServiceViewModel = new SmtpGlobalServiceViewModel()
            {
                SmtpServerAddress = emailService.SmtpServerAddress,
                SmtpPort = emailService.SmtpPort,
                AllowAnonymous = emailService.AllowAnonymous,
                EnableSSL = emailService.EnableSSL,
                Id = emailService.Id,
                SenderAddress = emailService.SenderAddress,
                SenderName = emailService.SenderName,
                SmtpAccount = emailService.SmtpAccount,
                SmtpPassword = emailService.SmtpPassword
            };

            if (smtpGlobalServiceViewModel == null)
            {
                return HttpNotFound();
            }
            return View(smtpGlobalServiceViewModel);
        }

        // GET: SmtpGlobalServiceViewModels/Create
        public ActionResult Create()
        {
            if (db.EmailService.Count() >= 1)
            {
                return Content("Global email service alreay exists!");
            }
            return View();
        }

        // POST: SmtpGlobalServiceViewModels/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(SmtpGlobalServiceViewModel model)
        {
            if (ModelState.IsValid && db.EmailService.Count() == 0)
            {
                var emailService = new EmailService()
                {
                    SenderAddress = model.SenderAddress,
                    SmtpPassword = model.SmtpPassword,
                    AllowAnonymous = model.AllowAnonymous,
                    CreateDate = DateTime.Now,
                    EnableSSL = model.EnableSSL,
                    SenderName = model.SenderName,
                    SmtpAccount = model.SmtpAccount,
                    SmtpPort = model.SmtpPort,
                    SmtpServerAddress = model.SmtpServerAddress,
                    UpdateDate = null,
                    //UserGroup = null
                };

                db.EmailService.Add(emailService);

                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(model);
        }

        // GET: SmtpGlobalServiceViewModels/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var emailService = db.EmailService.Find(id);

            if (emailService == null)
            {
                return HttpNotFound();
            }

            var model = new SmtpGlobalServiceViewModel()
            {
                SmtpServerAddress = emailService.SmtpServerAddress,
                SmtpPort = emailService.SmtpPort,
                AllowAnonymous = emailService.AllowAnonymous,
                EnableSSL = emailService.EnableSSL,
                Id = emailService.Id,
                SenderAddress = emailService.SenderAddress,
                SenderName = emailService.SenderName,
                SmtpAccount = emailService.SmtpAccount,
                SmtpPassword = emailService.SmtpPassword
            };

            return View(model);
        }

        // POST: SmtpGlobalServiceViewModels/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(SmtpGlobalServiceViewModel model)
        {
            if (ModelState.IsValid)
            {
                //db.Entry(smtpGlobalServiceViewModel).State = EntityState.Modified;

                var emailService = db.EmailService.Find(model.Id);

                if (emailService == null)
                {
                    return HttpNotFound();
                }
                
                emailService.AllowAnonymous = model.AllowAnonymous;
                emailService.EnableSSL = model.EnableSSL;
                emailService.SenderAddress = model.SenderAddress;
                emailService.SenderName = model.SenderName;
                emailService.SmtpAccount = model.SmtpAccount;
                emailService.SmtpPassword = model.SmtpPassword;
                emailService.SmtpPort = model.SmtpPort;
                emailService.SmtpServerAddress = model.SmtpServerAddress;
                emailService.UpdateDate = DateTime.Now;

                db.SaveChanges();

                return RedirectToAction("Index");
            }
            return View(model);
        }

        // GET: SmtpGlobalServiceViewModels/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var emailService = db.EmailService.Find(id);

            var smtpGlobalServiceViewModel = new SmtpGlobalServiceViewModel()
            {
                SmtpServerAddress = emailService.SmtpServerAddress,
                SmtpPort = emailService.SmtpPort,
                AllowAnonymous = emailService.AllowAnonymous,
                EnableSSL = emailService.EnableSSL,
                Id = emailService.Id,
                SenderAddress = emailService.SenderAddress,
                SenderName = emailService.SenderName,
                SmtpAccount = emailService.SmtpAccount,
                SmtpPassword = emailService.SmtpPassword
            };

            if (smtpGlobalServiceViewModel == null)
            {
                return HttpNotFound();
            }
            return View(smtpGlobalServiceViewModel);
        }

        // POST: SmtpGlobalServiceViewModels/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            var emailService = db.EmailService.FirstOrDefault(o => o.Id == id);

            if (emailService != null)
            {
                db.EmailService.Remove(emailService);
                db.SaveChanges();
            }
            else
            {
                return HttpNotFound();
            }

            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult SendTestEmail(int? id)
        {
            var emailService = db.EmailService.FirstOrDefault(o => o.Id == id);

            if (emailService == null)
            {
                return HttpNotFound();
            }

            var model = new SmtpGlobalServiceViewModel()
            {
                SmtpServerAddress = emailService.SmtpServerAddress,
                SmtpPort = emailService.SmtpPort,
                AllowAnonymous = emailService.AllowAnonymous,
                EnableSSL = emailService.EnableSSL,
                Id = emailService.Id,
                SenderAddress = emailService.SenderAddress,
                SenderName = emailService.SenderName,
                SmtpAccount = emailService.SmtpAccount,
                SmtpPassword = emailService.SmtpPassword
            };

            return View(model);
        }

        [HttpPost]
        public ActionResult SendTestEmail(int? id, string title, string body, string sendTo)
        {
            string TestMailMessage = "";

            var emailService = db.EmailService.FirstOrDefault(o => o.Id == id);

            if (emailService == null)
            {
                return HttpNotFound();
            }

            var model = new SmtpGlobalServiceViewModel()
            {
                SmtpServerAddress = emailService.SmtpServerAddress,
                SmtpPort = emailService.SmtpPort,
                AllowAnonymous = emailService.AllowAnonymous,
                EnableSSL = emailService.EnableSSL,
                Id = emailService.Id,
                SenderAddress = emailService.SenderAddress,
                SenderName = emailService.SenderName,
                SmtpAccount = emailService.SmtpAccount,
                SmtpPassword = emailService.SmtpPassword
            };

            try
            {
                //Send mail
                var smtp = emailService.CreateSmtpClient();

                using (var message = new MailMessage())
                {
                    message.From = new MailAddress(emailService.SmtpAccount, emailService.SenderName);

                    foreach (var to in sendTo.Split(';'))
                    {
                        message.To.Add(to);
                    }

                    message.Subject = "test title";
                    message.Body = "test body";

DsAdmin/Views/SmtpGlobal/Create.cshtml
@model DsAdmin.Models.ViewModels.SmtpGlobalServiceViewModel

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>SmtpGlobalServiceViewModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.SenderAddress, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SenderAddress, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SenderAddress, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SenderName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SenderName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SenderName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EnableSSL, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.EnableSSL)
                    @Html.ValidationMessageFor(model => model.EnableSSL, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SmtpPort, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SmtpPort, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SmtpPort, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SmtpServerAddress, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SmtpServerAddress, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SmtpServerAddress, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AllowAnonymous, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.AllowAnonymous)
                    @Html.ValidationMessageFor(model => model.AllowAnonymous, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SmtpAccount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SmtpAccount, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SmtpAccount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SmtpPassword, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SmtpPassword, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SmtpPassword, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

DsAdmin/Views/SmtpGlobal/Delete.cshtml
@model DsAdmin.Models.ViewModels.SmtpGlobalServiceViewModel

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>SmtpGlobalServiceViewModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.SenderAddress)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SenderAddress)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SenderName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SenderName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EnableSSL)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EnableSSL)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SmtpPort)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SmtpPort)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SmtpServerAddress)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SmtpServerAddress)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AllowAnonymous)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AllowAnonymous)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SmtpAccount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SmtpAccount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SmtpPassword)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SmtpPassword)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

DsAdmin/Views/SmtpGlobal/Details.cshtml
@model DsAdmin.Models.ViewModels.SmtpGlobalServiceViewModel

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>SmtpGlobalServiceViewModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.SenderAddress)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SenderAddress)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SenderName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SenderName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EnableSSL)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EnableSSL)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SmtpPort)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SmtpPort)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SmtpServerAddress)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SmtpServerAddress)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AllowAnonymous)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AllowAnonymous)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SmtpAccount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SmtpAccount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SmtpPassword)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SmtpPassword)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

DsAdmin/Views/SmtpGlobal/Edit.cshtml
@model DsAdmin.Models.ViewModels.SmtpGlobalServiceViewModel

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>SmtpGlobalServiceViewModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.SenderAddress, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SenderAddress, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SenderAddress, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SenderName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SenderName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SenderName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EnableSSL, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.EnableSSL)
                    @Html.ValidationMessageFor(model => model.EnableSSL, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SmtpPort, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SmtpPort, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SmtpPort, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SmtpServerAddress, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SmtpServerAddress, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SmtpServerAddress, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AllowAnonymous, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.AllowAnonymous)
                    @Html.ValidationMessageFor(model => model.AllowAnonymous, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SmtpAccount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SmtpAccount, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SmtpAccount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SmtpPassword, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SmtpPassword, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SmtpPassword, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

DsAdmin/Views/SmtpGlobal/Index.cshtml
@model IEnumerable<DsAdmin.Models.ViewModels.SmtpGlobalServiceViewModel>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

@if (ViewBag.ServiceCount == 0)
{
    <p>
        @Html.ActionLink("Create New", "Create")
    </p>
}
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.SenderAddress)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SenderName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EnableSSL)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SmtpPort)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SmtpServerAddress)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.AllowAnonymous)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SmtpAccount)
        </th>
        @*<th>
            @Html.DisplayNameFor(model => model.SmtpPassword)
        </th>*@
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.SenderAddress)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.SenderName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.EnableSSL)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.SmtpPort)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.SmtpServerAddress)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.AllowAnonymous)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.SmtpAccount)
        </td>
        @*<td>
            @Html.DisplayFor(modelItem => item.SmtpPassword)
        </td>*@
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id }) |
            @Html.ActionLink("Test", "SendTestEmail", new { id = item.Id })
        </td>
    </tr>
}

</table>

DsAdmin/Views/SmtpGlobal/SendTestEmail.cshtml
@model DsAdmin.Models.ViewModels.SmtpGlobalServiceViewModel

@{
    ViewBag.Title = "SendTestEmail";
}

<h2>Send Test Email</h2>

<dl class="dl-horizontal">
    <dt>
        @Html.DisplayNameFor(model => model.SmtpServerAddress)
    </dt>

    <dd>
        @Html.DisplayFor(model => model.SmtpServerAddress)
    </dd>

    <dt>
        @Html.DisplayNameFor(model => model.SmtpPort)
    </dt>

    <dd>
        @Html.DisplayFor(model => model.SmtpPort)
    </dd>

    <dt>
        @Html.DisplayNameFor(model => model.SmtpAccount)
    </dt>

    <dd>
        @Html.DisplayFor(model => model.SmtpAccount)
    </dd>

</dl>

<hr />

@using (Html.BeginForm("SendTestEmail", "SmtpGlobal", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <div class="form-group">
            <label class="control-label col-md-2">Send To</label>
            <div class="col-md-10">
                <input type="text" name="SendTo" value="" class="form-control" />
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-md-2">Title</label>
            <div class="col-md-10">
                <input type="text" name="title" value="" class="form-control" />
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-md-2">Content</label>
            <div class="col-md-10">
                <input type="text" name="body" value="" class="form-control" />
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <button class="btn btn-success">Send</button>
            </div>
        </div>
    </div>
    <hr />
    
}

<p>
    @Html.ActionLink("Back to List", "Index")
</p>

@if (ViewBag.TestMailMessage != null)
{
    <script>
        alert("@ViewBag.TestMailMessage.ToString()")
    </script>
}